nginx:
    image: finney/nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    image: finney/counter
    links:
        - redis
    ports:
        - "5000"
node2:
    image: finney/counter
    links:
        - redis
    ports:
        - "5000"
node3:
    image: finney/counter
    links:
        - redis
    ports:
        - "5000"
redis:
    image: redis
    ports:
        - "6379"
