# Set the base image to Ubuntu
FROM redis

# File Author / Maintainer
MAINTAINER Sean Finney

RUN apt-get update && apt-get install -y unzip
RUN cd /usr/local/bin && \
  wget https://releases.hashicorp.com/consul/0.8.3/consul_0.8.3_linux_amd64.zip && \
  unzip consul_0.8.3_linux_amd64.zip

CMD redis-server
